version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
